version: '3.8'
services:
  spark-master:
    build: .
    image: custom-spark:latest
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
      HOME: /home/sparkuser
    ports:
      - "8080:8080" # Spark master web UI
      - "7077:7077" # Spark master port
    networks:
      - spark-net

  spark-worker-1:
    build: .
    image: custom-spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - IVY_HOME=/opt/bitnami/spark/tmp/.ivy2
      - SPARK_LOCAL_DIRS=/opt/bitnami/spark/tmp/spark
      - SPARK_NETWORK_IO_FRAME_SIZE=128m
      - SPARK_NETWORK_IO_MAXRETRIES=10
      - SPARK_NETWORK_IO_CONNECTIONTIMEOUT=60000
      - SPARK_RPC_MESSAGE_MAXSIZE=134217728
      - SPARK_NETWORK_MAXREMOTEBLOCKSIZEFETCHTOMEM=134217728
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-2:
    build: .
    image: custom-spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - IVY_HOME=/opt/bitnami/spark/tmp/.ivy2
      - SPARK_LOCAL_DIRS=/opt/bitnami/spark/tmp/spark
      - SPARK_NETWORK_IO_FRAME_SIZE=128m
      - SPARK_NETWORK_IO_MAXRETRIES=10
      - SPARK_NETWORK_IO_CONNECTIONTIMEOUT=60000
      - SPARK_RPC_MESSAGE_MAXSIZE=134217728
      - SPARK_NETWORK_MAXREMOTEBLOCKSIZEFETCHTOMEM=134217728
    depends_on:
      - spark-master
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
